# https://travis-ci.com/opensourcewebsite-org/php-telegram-sdk
# https://docs.travis-ci.com
sudo: false
language: php
dist: bionic
php:
  - 7.4
matrix:
  fast_finish: true
  allow_failures:
    - php: master
install:
  - composer install --prefer-dist --no-interaction
before_script:
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
  - ./vendor/bin/php-cs-fixer fix --verbose --dry-run
  - ./vendor/bin/phpunit --coverage-text
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor
